Add OwnerReferences for sysprom resources
platform9/prometheus-plus pull request #14
Opened 2019-12-26 14:12 UTC by mugdha-adhav

## DESCRIPTION
- Add monhelper as owner of sysprom resources
- Refactored code

## ISSUE(S):

[MA-131](https://platform9.atlassian.net/projects/MA/issues/MA-131): Clean resources created by monhelper on delete API call in appbert
[MA-126](https://platform9.atlassian.net/projects/MA/issues/MA-126): system prometheus and grafana pods not deleted after removing pf9-mon package

## ISSUE TYPE
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTING
- Manual: Tested on minikube cluster
- Automated: Yet to be tested on PMK cluster

2019-12-28 01:03 UTC, smanpathak requested changes

2019-12-28 01:03 UTC, smanpathak commented on pkg/sysprom/initialize_test.go
> +	}, nil
error return value always null

2019-12-30 08:54 UTC, mugdha-adhav commented on pkg/sysprom/initialize_test.go
> +	}, nil
I have removed the error return value as it is not required.

2019-12-30 17:02 UTC, smanpathak approved these changes

2019-12-30 18:31 UTC, merged