Added a new switch to deploy system prometheus instance
platform9/prometheus-plus pull request #2
Opened 2019-09-04 09:26 UTC by mayuresh108

2019-09-04 11:03 UTC, mugdha-adhav approved these changes

2019-09-04 21:45 UTC, smanpathak requested changes
Please put up a description, testing done.

2019-09-05 05:27 UTC, mayuresh108 commented
> Please put up a description, testing done.

Manually tested these changes with appbert. When prometheus operator is enabled from the UI, the monhelper binary is invoked with the new switch "--initmode=true" and it waits for CRDs. Then it installs an instance of Prometheus, service monitor, alert manager and grafana. The grafana UI is accessible from the DU UI through qbert (with recent qbert bug fixes)

2019-09-06 20:33 UTC, smanpathak requested changes

2019-09-06 20:33 UTC, smanpathak commented on promplus/grafana-datasources
> +            "url": "http://prometheus.pf9-operators.svc:9090",
I thought this is moving to pf9-monitoring?

2019-09-06 20:34 UTC, smanpathak approved these changes

2019-09-06 20:34 UTC, smanpathak approved these changes

2019-09-07 10:53 UTC, merged